# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('idCard', models.ImageField(upload_to=b'')),
                ('type', models.CharField(choices=[('s', 'Self'), ('g', 'Group'), ('c', 'Cooperate'), ('o', 'Others')], default='s', max_length=2)),
                ('tickets', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
